IF @FileCategory = 'VEHICLE'
BEGIN
	SELECT COUNT(*)
	FROM tblRAW_VEHMAS WITH(NOLOCK)
	WHERE HdrId = @HeaderID
END
ELSE IF @FileCategory = 'CUSTOMER'
BEGIN
	SELECT COUNT(*)
	FROM tblWIP_CUSMAS WITH(NOLOCK)
	WHERE HdrId = @HeaderID
END
IF @FileCategory = 'CARLINE'
BEGIN
	SELECT COUNT(*)
	FROM tblWIP_Carline WITH(NOLOCK)
	WHERE HdrId = @HeaderID
END
ELSE IF @FileCategory = 'PRODMASTER'
BEGIN
	SELECT COUNT(*)
	FROM tblWIP_ProdMas WITH(NOLOCK)
	WHERE HdrId = @HeaderID
END
ELSE IF @FileCategory = 'NVINVBK'
BEGIN
	SELECT COUNT(*)
	FROM tblWIP_NVINVBK WITH(NOLOCK)
	WHERE HdrId = @HeaderID
END
ELSE IF @FileCategory = 'ACCOUNTS'
BEGIN

	SELECT COUNT(*)
	FROM tblWIP_Accounts 
	WHERE HdrId = @HeaderID
END
