IF @FileCategory = 'CARLINE'
BEGIN
	SELECT [ID], [CLN.DESC] AS [DESC]
	FROM tblWIP_Carline WITH(NOLOCK)
	WHERE HdrId = @HeaderID
END
ELSE IF @FileCategory = 'PRODMASTER'
BEGIN
	--SELECT ID
	--	, [MST.DESC] AS [DESC]
	--FROM tblWIP_ProdMas WITH(NOLOCK)
	--WHERE HdrId = @HeaderID
	
	SELECT
		LTRIM(RTRIM(COALESCE([MST.SORTKEY], ID, ''))) AS ID					--PART NO
		, LTRIM(RTRIM([MST.DESC])) AS [DESC]				--DESCRIPTION
		, [MST.BASE.LIST] AS RetailPrice	--SRP
		, [MST.BASE.COST] AS Cost			--COST
		, [MST.BASE.WARR] AS Warranty		--WARR
		, [MST.NEW.NO] AS SubPartNo			--SUBSTITUTE PART NUMBER
		, [MST.MDL.APPLN] AS ModelCode		--MODEL CODE
		--, [MST.MOVEMENT.CODE]--MOVEMENT CODE
		, CAST([MST.SRC] AS NVARCHAR) AS SCC--SOURCE CODE
	FROM tblWIP_ProdMas
	WHERE HdrId = @HeaderID
	
END
ELSE IF @FileCategory = 'NVINVBK'
BEGIN
	SELECT ID	
		, [VNV.DESC] AS [DESC]
	FROM tblWIP_NVINVBK WITH(NOLOCK)
	WHERE HdrId = @HeaderID
END
ELSE IF @FileCategory = 'NVMODEL'
BEGIN
	SELECT ID
		,[NVM.DESC] AS [DESC]
	FROM tblWIP_NVModelMas
	WHERE HdrId = @HeaderID
END

ELSE IF @FileCategory = 'ACCTGMAP'
BEGIN
	SELECT SrcAccNo AS ID
		,DstAccNo AS [DESC]
	FROM tblWIP_AcctgMap
	WHERE HdrId = @HeaderID
END

ELSE IF @FileCategory = 'SERVICEMODEL'
BEGIN
	SELECT ID
		,[SRM.DESC] AS [DESC]
	FROM tblWIP_SERVICEMODEL
	WHERE HdrId = @HeaderID
END

ELSE IF @FileCategory = 'SERVCODE'
BEGIN
	SELECT [SRC.MDL.CODE] AS ID
		,[SRC.OP.DESC] AS [DESC]
	FROM tblWIP_SERVCODE
	WHERE HdrId = @HeaderID
END

ELSE IF @FileCategory = 'VEHCOLOR'
BEGIN
	SELECT WIP.ID
		,[VCL.DESC] AS [DESC]
		, FieldValue AS OtherInfo
	FROM tblWIP_VEHCOLOR WIP WITH(NOLOCK)
	LEFT JOIN RMULTIVALUED M WITH(NOLOCK)
		ON WIP.HDRID = M.HeaderID AND WIP.ID = M.ID
	WHERE HdrId = @HeaderID
		AND FIELDNAME = 'VCL.MODEL'
END
ELSE IF @FileCategory = 'RELEASEDSTOCK'
BEGIN
	SELECT	VIN AS ID,
			'' AS [Desc],
			'' AS OtherInfo
	FROM tblWIP_ReleasedStock WITH(NOLOCK)
	WHERE 1=0
END
ELSE IF @FileCategory = 'TFREESTOCK'
BEGIN
	SELECT	VIN AS ID,
			'' AS [Desc],
			'' AS OtherInfo
	FROM tblWIP_TFreeStock WITH(NOLOCK)
	WHERE 1=0
END