SELECT CM.COLCDE AS ID
	, CM.COL AS [DESC]
	, [ERAModelCode] AS OtherInfo
FROM mModelCode MC WITH(NOLOCK)
LEFT JOIN AS400PSS.B6091760.[@PSDTA].PSRBDY MM 
	ON MC.[TMPModelCode] = MM.MODCDE
LEFT JOIN AS400PSS.B6091760.[@PSDTA].PSRCLR CM
	ON MM.BDYTYP = CM.APPBDY