SELECT  REPLACE(REPLACE(WMI, '.', ''), ',','') || REPLACE(FRAME_PREF,'.','') || REPLACE(CHECK_DIGIT, '.', '') || REPLACE(BODY_NO, '.', '') as VIN
,REPLACE(REPLACE(ENGINE_PREF, '.', ''), ',','') || ENGINE_NO AS ENGINENO
,CS_NO AS CSNO
FROM VEHICLE_MASTER
WHERE CONDITION_CODE NOT IN ('GARBAGE')
